version: '3.8'

services:
  content-moderation-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - .:/app

volumes:
  ollama_data: